name: Publish Artifact to Reposilite (Manual)

on:
  workflow_dispatch:

jobs:
  deploy-to-reposilite:
    name: Deploy Artifact to Reposilite
    runs-on: java21-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          overwrite-settings: false

      - name: Configure Maven for Reposilite
        run: |
          SETTINGS_FILE="${{ runner.temp }}/settings.xml"
          
          echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'
                xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd'>
              <servers>
                <server>
                  <id>reposilite</id>
                  <username>${{ secrets.REPOSILITE_USERNAME }}</username>
                  <password>${{ secrets.REPOSILITE_PASSWORD }}</password>
                </server>
              </servers>
            </settings>" > "$SETTINGS_FILE"

          echo "MAVEN_SETTINGS_PATH=$SETTINGS_FILE" >> $GITHUB_ENV
          echo "✅ Maven settings.xml created for Reposilite."

      - name: Get Version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn --settings ${{ env.MAVEN_SETTINGS_PATH }} help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Deploy with Maven
        run: |
          set -euo pipefail
          VERSION="${{ steps.get_version.outputs.VERSION }}"

          echo "Deploying version $VERSION to Reposilite..."  
          mvn --settings ${{ env.MAVEN_SETTINGS_PATH }} deploy
          echo "✅ Artifact version $VERSION successfully deployed."