name: Publish Artifact to Reposilite (Manual)

on:
  workflow_dispatch:

jobs:
  deploy-to-reposilite:
    name: Deploy Artifact to Reposilite
    runs-on: java21-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create Maven settings.xml
        run: |
          SETTINGS_FILE="${{ runner.temp }}/settings.xml"
          echo "<settings xmlns='http://maven.apache.org/SETTINGS/1.0.0'
                xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd'>
              <servers>
                <server>
                  <id>reposilite</id>
                  <username>${{ secrets.REPOSILITE_USERNAME }}</username>
                  <password>${{ secrets.REPOSILITE_PASSWORD }}</password>
                </server>
              </servers>
            </settings>" > "$SETTINGS_FILE"
          echo "✅ Maven settings.xml created"

      - name: Get Version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Deploy with Maven
        run: |
          set -euo pipefail
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          SETTINGS_FILE="${{ runner.temp }}/settings.xml"

          echo "Deploying version $VERSION to Reposilite..."

          mvn deploy -s "$SETTINGS_FILE"

          echo "✅ Artifact version $VERSION successfully deployed."